name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.0'

      - name: Install dependencies
        run: |
          pip install flake8

      - name: Ensure required directories exist
        run: |
          mkdir -p notebooks scripts

      - name: Run flake8
        run: |
          flake8 notebooks scripts
